[build]
  publish = ".next"
  command = "rm -rf node_modules && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirections for the API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirections for the webhooks
[[redirects]]
  from = "/webhooks/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=()"
    Content-Security-Policy = "default-src 'self' *.chefito.xyz; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.chefito.xyz; style-src 'self' 'unsafe-inline' *.chefito.xyz fonts.googleapis.com; img-src 'self' data: https: *.chefito.xyz *.pexels.com; font-src 'self' data: *.chefito.xyz fonts.gstatic.com; connect-src 'self' *.chefito.xyz wss: https:; media-src 'self' *.chefito.xyz; frame-src 'self' *.chefito.xyz;"

# CORS pour les API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://chefito.xyz, https://app.chefito.xyz, https://admin.chefito.xyz"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"

# CORS pour les webhooks
[[headers]]
  for = "/webhooks/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configuration PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"